### ISSUE TITLE
Comentarios de red social sprint 1

### ISSUE THREAD

**Issue by Jonhks** [sanrey254/proyecto-3-social-network#11]
@sanrey254 , @Dani1592 

- Buen uso de issues. 
-  Creo que no se alcanza a ver el archivo style.css en el timeLine.html, por los "../" (la ruta de .css).
- Buena investigación al usar (https://cdn.jsdelivr.net/npm/sweetalert2").
-  Podrían mejorar el diseño mobile para no usar el scroll en celulares de la pantalla principal. 
- Los botones me parecen muy cuadrados, para mi gusto. 
- La imagen de la pantalla registrare no se ve. 
- Si le doy click a ingresa en la pantalla de registrate, me marca un error 404. 
- El botón de google no hace nada. 
- El botón de facebook no hace nada. 
- En la pantalla principal google dice que la aplicación no esta verificada. 
- Muy buen avance chicas, creo que solo faltan unas pequeñas verificaciones de los inputs en el login. 
- Quizá cambiar la estructura de las publicaciones.

**Comment by sanrey254** [comment]
Gracias por las observaciones, la mayoría de ellas ya están solucionadas.
